# Generated by Django 4.2.7 on 2025-03-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=42)),
                ('transaction_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('amount', models.DecimalField(decimal_places=10, default=0.0001, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['wallet_address'], name='faucet_tran_wallet__c49ff4_idx'), models.Index(fields=['status'], name='faucet_tran_status_5d1276_idx'), models.Index(fields=['created_at'], name='faucet_tran_created_d24396_idx'), models.Index(fields=['ip_address'], name='faucet_tran_ip_addr_2f96ca_idx'), models.Index(fields=['updated_at'], name='faucet_tran_updated_738818_idx'), models.Index(fields=['priority'], name='faucet_tran_priorit_d9a7dc_idx')],
            },
        ),
    ]
